language: java
sudo: false
jdk:
- oraclejdk7
install: true
script: "./gradle/buildViaTravis.sh"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_d609e95af532_key -iv $encrypted_d609e95af532_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/80c005f86406b32383e0
    on_success: change
    on_failure: always
    on_start: never
